### ISSUE TITLE
Lack of masked depth map

### ISSUE THREAD

**Issue by hu2011** [ShreyasSkandanS/stereo_sparse_depth_fusion#3]
Hi, 
the masked depth used in your fusion code is from the ground truth disparity in stereo2015. For the normal sensor data, it don't have ground truth disparity image. Can you tell me how to implement the fusion algorithm on Raw data of KITTI(without ground truth disparity image, only left-right camera and lidar)? 
	
I have transformed the 3D lidar points to depth value, and disparity = (f_u*baseline)/z as masked depth. however, the fused results are bad, worse than the original sgm. Or can you share the script which you used to produce the PMD Monstar Dataset? In you paper,you also get disparity from the depth meansurements and it seems to be a success, thanks a lot.

**Comment by ShreyasSkandanS** [comment]
Hi @hu2011, can you post a few examples of the bad fusion results with the raw KITTI data. I used the Stereo 2015 dataset for this work because the "bad" LiDAR measurements have been removed from the Ground Truth measurements, whereas I believe the raw data is not filtered. This could potentially cause poor disparity images. If you post a few examples I'm happy to take a look.

**Comment by hu2011** [comment]
Hi @ShreyasSkandanS yes, you are right. There is  big difference between the obtained disparity from raw lidar and ground truth disparity. For example(2011_09_26_drive_0009_sync frame 384,  is 000010_10.png in stereo2015), here are 22 thousand  points on left image from lidar, but only 9 thousand efficent points on the same coordinates on ground truth disparity. It is almost impossible to get the same results from the raw lidar data.
	
The bad fused image (from diffusion )is like this:
![diffusion_based](https://user-images.githubusercontent.com/29193740/67446597-b4ea3380-f643-11e9-84d6-a2aea06f6f2a.png)

**Comment by hu2011** [comment]
Hi @ShreyasSkandanS , I'm so sorry for getting wrong velodyne frame by pykitti(384). The new result is shown below, and it looks a little better, still need some postprocess. 
![diffusion_based1](https://user-images.githubusercontent.com/29193740/67468395-0236c700-f67d-11e9-8b1a-3041320eec2f.png)

**Comment by ShreyasSkandanS** [comment]
> Hi @ShreyasSkandanS , I'm so sorry for getting wrong velodyne frame by pykitti(384). The new result is shown below, and it looks a little better, still need some process.
> ![diffusion_based1](https://user-images.githubusercontent.com/29193740/67468395-0236c700-f67d-11e9-8b1a-3041320eec2f.png)
> 
> using the obtained disparity from lidar and the gt_disparity as evaluation reference. the run results:
> {EVALUATION A:} -- SEMI GLOBAL MATCHING --
> {status} no fusion. Semi global matching only..
> Total ground truth points: 111664
> {SGM} avg error: 1.2602
> 
> {EVALUATION B:} -- NAIVE LIDAR FUSION --
> Total ground truth points: 111664
> {NAIVE FUSION} avg error: 1.20339
> 
> {EVALUATION C:} -- DIFFUSION BASED --
> Total ground truth points: 111664
> {DB} avg error: 0.953724
> 
> {EVALUATION D:} -- NEIGHBORHOOD SUPPORT --
> Total ground truth points: 111664
> {NS} avg error: 0.9042

This looks more reasonable, but the output of this - is this from SGM only? or is this one **Evaluation C** or **Evaluation D**?

**Comment by hu2011** [comment]
Hi @ShreyasSkandanS , this result is from DIFFUSION BASED FUSION (evaluation C). Do you have any suggestions to get a better disparity image like in your paper? Thanks

**Comment by ShreyasSkandanS** [comment]
Hi @hu2011,

Could you post pictures of the following: Input RGB image, Sparse Depth input, Semi Global Matching and Diffusion Based fusion?

Best regards,
Shreyas

**Comment by hu2011** [comment]
@ShreyasSkandanS hi, sorry for late reply.
Input left RGB
![stereo_left](https://user-images.githubusercontent.com/29193740/67670631-4a245980-f9af-11e9-805a-921e92385290.png)
right RGB image
![stereo_right](https://user-images.githubusercontent.com/29193740/67671878-b0aa7700-f9b1-11e9-8997-aa29eb235116.png)

Input sparse depth (from lidar, maybe too sparse to see)
![gt2_disparity](https://user-images.githubusercontent.com/29193740/67670611-3aa51080-f9af-11e9-89b8-2167e988c24a.png)

Output of sgm
![sgm_default](https://user-images.githubusercontent.com/29193740/67670593-2d882180-f9af-11e9-824f-0071f8074c2b.png)

output of diffusion based fusion. It is strange that here is very bright area (disparity values > 240) on the right signal light.
![fuse_diffusionbased](https://user-images.githubusercontent.com/29193740/67670601-32e56c00-f9af-11e9-8927-219d8cf23db1.png)

**Comment by ShreyasSkandanS** [comment]
This might have something to do with the input LiDAR scan. But the fusion seems to be working (if you look at the circular arrow sign). The errors at the top of the image appear to just be problems with SGM in those regions. They aren't improved because there are no LiDAR points there.

**Comment by ShreyasSkandanS** [comment]
Since this is no longer an issue related to this work, I am proceeding to close this. If you have any other issues, please feel free to raise another issue. Best regards, SS.
