### ISSUE TITLE
execution time

### ISSUE THREAD

**Issue by LeRoii** [ShreyasSkandanS/stereo_sparse_depth_fusion#4]
hi, I tried out your code on a VMware virtual machine with ubuntu 16.04,
the result was good but the average execution time was about 2-3 ms/frame, 
I wonder if this is normal, because on paper you said the entire pipeline can run at 5Hz
![image](https://user-images.githubusercontent.com/23433742/69227839-7cdffd00-0bbd-11ea-97ad-9961fb7e1dff.png)

**Comment by ShreyasSkandanS** [comment]
Hi @LeRoii, yes, you are correct. This implementation of SGM is a CPU-based implementation and takes about 1-2 seconds. However, if you use a GPU-accelerated version of SGM such as this (https://github.com/dhernandez0/sgm) you can get speeds of >= 5Hz on an embedded GPU such as the TX2, Xavier. We provide this version of SGM as I believe it is one of the most accurate implementations of the original paper by Hirschmüller.
