### ISSUE TITLE
SGM aggregation directions

### ISSUE THREAD

**Issue by LeRoii** [ShreyasSkandanS/stereo_sparse_depth_fusion#5]
hi, in paper you said you used 4-8 directions, but I can't see very clear in your code about the aggregation direction, could you explain a little about this part, about the function calcTopRowCost() and calcRowCosts()

**Comment by ShreyasSkandanS** [comment]
Hi @LeRoii, I believe you are referring to the code from the SGM implementation that I used (https://ttic.uchicago.edu/~dmcallester/SPS/index.html). However, I can try to answer the questions that you have but if it is primarily implementation questions regarding the two functions **calcTopRowCost()** and **calcRowCosts()** your best bet is to e-mail the authors of that implementation.

Regarding your first question, yes I did experiment with both 4 and 8 way directions. However for the final evaluations I used 8 across all comparisons (default settings in the code provided).
